const getDummyWeatherData = async () => {
  return new Promise((resolve) => {
    resolve({
      location: {
        address: "123 Lake Road, Alabama 36601, United States",
        addressText: "Lake Road",
        city: "Lakeville",
        state: "Alabama 36601",
        stateAbbr: "AL",
        displayCityState: "Lakeville, Alabama",
      },
      weatherData: [
        {
          cloud_cover: "0%",
          air_quality: "48 AQI",
          dew_point: "48 °F",
          datetime: "2023-02-20T00:00:00.000Z",
          part_of_day: "Night",
          precipitation: "0.00 in",
          pressure: "1017 hPa",
          snowfall: "0.00 in",
          weather_station: "G2175",
          sunrise: null,
          sunset: null,
          temperature: "55 °F",
          feels_like: "55 °F",
          timezone: "America/Chicago",
          uv_index: 0,
          weather_description: "Clear sky",
          wind_direction: "179°",
          wind_speed: "4 mph",
          max_wind_speed_gust: "15 mph",
          high_temp: null,
          low_temp: null,
        },
        {
          cloud_cover: "23%",
          air_quality: " AQI",
          dew_point: "44 °F",
          datetime: "2023-02-19T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1018.8 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "53 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 5.9,
          weather_description: "Scattered clouds",
          wind_direction: "194°",
          wind_speed: "5 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "64 °F",
          low_temp: "51 °F",
        },
        {
          cloud_cover: "61%",
          air_quality: " AQI",
          dew_point: "56 °F",
          datetime: "2023-02-20T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1012.1 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "60 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 3.3,
          weather_description: "Broken clouds",
          wind_direction: "228°",
          wind_speed: "9 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "67 °F",
          low_temp: "62 °F",
        },
        {
          cloud_cover: "96%",
          air_quality: " AQI",
          dew_point: "63 °F",
          datetime: "2023-02-21T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1009.2 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "64 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 2.6,
          weather_description: "Overcast clouds",
          wind_direction: "214°",
          wind_speed: "10 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "69 °F",
          low_temp: "62 °F",
        },
        {
          cloud_cover: "59%",
          air_quality: " AQI",
          dew_point: "66 °F",
          datetime: "2023-02-22T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1011.7 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "70 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 6.1,
          weather_description: "Broken clouds",
          wind_direction: "178°",
          wind_speed: "11 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "76 °F",
          low_temp: "68 °F",
        },
        {
          cloud_cover: "73%",
          air_quality: " AQI",
          dew_point: "68 °F",
          datetime: "2023-02-23T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1016 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "71 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 5.5,
          weather_description: "Overcast clouds",
          wind_direction: "184°",
          wind_speed: "8 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "79 °F",
          low_temp: "69 °F",
        },
        {
          cloud_cover: "68%",
          air_quality: " AQI",
          dew_point: "66 °F",
          datetime: "2023-02-24T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1019.8 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "71 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 6.3,
          weather_description: "Broken clouds",
          wind_direction: "185°",
          wind_speed: "5 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "79 °F",
          low_temp: "65 °F",
        },
        {
          cloud_cover: "51%",
          air_quality: " AQI",
          dew_point: "65 °F",
          datetime: "2023-02-25T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1016.6 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "70 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 6.5,
          weather_description: "Broken clouds",
          wind_direction: "167°",
          wind_speed: "7 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "77 °F",
          low_temp: "66 °F",
        },
      ],
    });
  });
};

module.exports = {
  getDummyWeatherData,
};
