const getDummyWeatherData = async () => {
  return new Promise((resolve) => {
    resolve({
      location: {
        address: "123 Lake Road, Alabama 36601, United States",
        addressText: "Lake Road",
        city: "Lakeville",
        state: "Alabama 36601",
        stateAbbr: "AL",
        displayCityState: "Lakeville, Alabama",
      },
      weatherData: [
        {
          id: "07241afc-c392-454b-8f5e-075f1d4e1e9e",
          cloud_cover: "0%",
          air_quality: "25 AQI",
          dew_point: "52 °F",
          datetime: "2023-02-20T00:00:00.000Z",
          part_of_day: "Night",
          precipitation: "0.00 in",
          pressure: "1016.5 hPa",
          snowfall: "0.00 in",
          weather_station: "G2175",
          sunrise: null,
          sunset: null,
          temperature: "54 °F",
          feels_like: "54 °F",
          timezone: "America/Chicago",
          uv_index: 0,
          weather_description: "Clear sky",
          wind_direction: "194°",
          wind_speed: "3 mph",
          max_wind_speed_gust: "10 mph",
          high_temp: null,
          low_temp: null,
        },
        {
          id: "b1131758-9c17-4678-8a9a-fede2d69dd98",
          cloud_cover: "2%",
          air_quality: " AQI",
          dew_point: "46 °F",
          datetime: "2023-02-19T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1016.5 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "57 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 5.6,
          weather_description: "Few clouds",
          wind_direction: "212°",
          wind_speed: "7 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "64 °F",
          low_temp: "51 °F",
        },
        {
          id: "634f8571-916a-4e3a-9044-e95ee4e743bd",
          cloud_cover: "39%",
          air_quality: " AQI",
          dew_point: "56 °F",
          datetime: "2023-02-20T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1011.8 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "60 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 3.5,
          weather_description: "Scattered clouds",
          wind_direction: "228°",
          wind_speed: "10 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "68 °F",
          low_temp: "62 °F",
        },
        {
          id: "13d5c264-7fb2-49b9-81d7-0403584d45f9",
          cloud_cover: "97%",
          air_quality: " AQI",
          dew_point: "64 °F",
          datetime: "2023-02-21T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1008.9 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "65 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 3.1,
          weather_description: "Overcast clouds",
          wind_direction: "215°",
          wind_speed: "11 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "68 °F",
          low_temp: "62 °F",
        },
        {
          id: "08407402-f85a-497c-8d54-5c2def51307e",
          cloud_cover: "59%",
          air_quality: " AQI",
          dew_point: "66 °F",
          datetime: "2023-02-22T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1011.5 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "69 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 5.4,
          weather_description: "Broken clouds",
          wind_direction: "179°",
          wind_speed: "11 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "76 °F",
          low_temp: "67 °F",
        },
        {
          id: "164d1d05-60ef-421c-85ca-09fa53cd6cad",
          cloud_cover: "68%",
          air_quality: " AQI",
          dew_point: "67 °F",
          datetime: "2023-02-23T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1015.6 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "71 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 5.3,
          weather_description: "Broken clouds",
          wind_direction: "185°",
          wind_speed: "8 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "78 °F",
          low_temp: "68 °F",
        },
        {
          id: "5725f8b0-99a8-4e89-b84f-715079e7914c",
          cloud_cover: "86%",
          air_quality: " AQI",
          dew_point: "65 °F",
          datetime: "2023-02-24T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1020.8 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "70 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 6.3,
          weather_description: "Overcast clouds",
          wind_direction: "186°",
          wind_speed: "3 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "74 °F",
          low_temp: "64 °F",
        },
        {
          id: "d01c7cc5-6337-4bad-8da0-681e12ef4717",
          cloud_cover: "48%",
          air_quality: " AQI",
          dew_point: "63 °F",
          datetime: "2023-02-25T00:00:00.000Z",
          part_of_day: null,
          precipitation: "0.00 in",
          pressure: "1020.1 hPa",
          snowfall: "0.00 in",
          weather_station: "",
          sunrise: null,
          sunset: null,
          temperature: "69 °F",
          feels_like: "N/A",
          timezone: "N/A",
          uv_index: 6.6,
          weather_description: "Broken clouds",
          wind_direction: "160°",
          wind_speed: "6 mph",
          max_wind_speed_gust: "0 mph",
          high_temp: "77 °F",
          low_temp: "65 °F",
        },
      ],
    });
  });
};

module.exports = {
  getDummyWeatherData,
};
