const {
  celsiusToFahrenheit,
  centimetersToInches,
  msToMph,
} = require("./utils/unit-conversion");

let data = {
  location: {
    address:
      "29150 Lake Forest Boulevard, Daphne, Alabama 36526, United States",
    addressText: "Lake Forest Boulevard",
    city: "Daphne",
    state: "Alabama 36526",
    stateAbbr: "AL",
    displayCityState: "Daphne, Alabama",
  },
  currentWeather: {
    app_temp: 16.7,
    aqi: 45,
    city_name: "Park City",
    clouds: 24,
    country_code: "US",
    datetime: "2023-02-19:22",
    dewpt: 9.9,
    dhi: 79.01,
    dni: 686.53,
    elev_angle: 19.89,
    ghi: 305.52,
    gust: 5.1875,
    h_angle: 60,
    lat: 30.6503,
    lon: -87.9075,
    ob_time: "2023-02-19 22:34",
    pod: "d",
    precip: 0,
    pres: 1016.5,
    rh: 64,
    slp: 1017.2208,
    snow: 0,
    solar_rad: 303.6,
    sources: ["rtma"],
    state_code: "AL",
    station: "G2175",
    sunrise: "12:27",
    sunset: "23:42",
    temp: 16.7,
    timezone: "America/Chicago",
    ts: 1676846075,
    uv: 1.4677285,
    vis: 16,
    weather: {
      description: "Few clouds",
      icon: "c02d",
      code: 801,
    },
    wind_cdir: "SSW",
    wind_cdir_full: "south-southwest",
    wind_dir: 213,
    wind_spd: 3.0308385,
  },
  futureWeather: {
    city_name: "Park City",
    country_code: "US",
    data: [
      {
        app_max_temp: 17.7,
        app_min_temp: 1.2,
        clouds: 23,
        clouds_hi: 37,
        clouds_low: 5,
        clouds_mid: 16,
        datetime: "2023-02-19",
        dewpt: 6.4,
        high_temp: 17.7,
        low_temp: 10.5,
        max_dhi: null,
        max_temp: 17.7,
        min_temp: 4.9,
        moon_phase: 0.00932925,
        moon_phase_lunation: 0.99,
        moonrise_ts: 1676809104,
        moonset_ts: 1676852637,
        ozone: 243,
        pop: 0,
        precip: 0,
        pres: 1018.8,
        rh: 71,
        slp: 1024.3,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1676809711,
        sunset_ts: 1676850253,
        temp: 11.7,
        ts: 1676790060,
        uv: 5.9,
        valid_date: "2023-02-19",
        vis: 23.846,
        weather: {
          code: 802,
          icon: "c02d",
          description: "Scattered clouds",
        },
        wind_cdir: "SSW",
        wind_cdir_full: "south-southwest",
        wind_dir: 194,
        wind_gust_spd: 3.3,
        wind_spd: 2.1,
      },
      {
        app_max_temp: 19.5,
        app_min_temp: 10.5,
        clouds: 61,
        clouds_hi: 81,
        clouds_low: 54,
        clouds_mid: 0,
        datetime: "2023-02-20",
        dewpt: 13.3,
        high_temp: 19.4,
        low_temp: 16.9,
        max_dhi: null,
        max_temp: 19.4,
        min_temp: 10.5,
        moon_phase: 0.00932925,
        moon_phase_lunation: 0.02,
        moonrise_ts: 1676897953,
        moonset_ts: 1676939037,
        ozone: 241.7,
        pop: 20,
        precip: 0.020992279,
        pres: 1012.1,
        rh: 88,
        slp: 1018.1,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1676896053,
        sunset_ts: 1676936699,
        temp: 15.3,
        ts: 1676872860,
        uv: 3.3,
        valid_date: "2023-02-20",
        vis: 14.301,
        weather: {
          code: 803,
          icon: "c03d",
          description: "Broken clouds",
        },
        wind_cdir: "SW",
        wind_cdir_full: "southwest",
        wind_dir: 228,
        wind_gust_spd: 7.4,
        wind_spd: 3.9,
      },
      {
        app_max_temp: 20.4,
        app_min_temp: 16.8,
        clouds: 96,
        clouds_hi: 23,
        clouds_low: 96,
        clouds_mid: 0,
        datetime: "2023-02-21",
        dewpt: 17.3,
        high_temp: 20.3,
        low_temp: 16.8,
        max_dhi: null,
        max_temp: 20.3,
        min_temp: 16.8,
        moon_phase: 0.0467159,
        moon_phase_lunation: 0.06,
        moonrise_ts: 1676986504,
        moonset_ts: 1677029554,
        ozone: 247.3,
        pop: 30,
        precip: 1.2156372,
        pres: 1009.2,
        rh: 96,
        slp: 1014.3,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1676982394,
        sunset_ts: 1677023144,
        temp: 18,
        ts: 1676959260,
        uv: 2.6,
        valid_date: "2023-02-21",
        vis: 11.716,
        weather: {
          code: 804,
          icon: "c04d",
          description: "Overcast clouds",
        },
        wind_cdir: "SW",
        wind_cdir_full: "southwest",
        wind_dir: 214,
        wind_gust_spd: 9.2,
        wind_spd: 4.3,
      },
      {
        app_max_temp: 24.9,
        app_min_temp: 17.3,
        clouds: 59,
        clouds_hi: 81,
        clouds_low: 58,
        clouds_mid: 6,
        datetime: "2023-02-22",
        dewpt: 18.9,
        high_temp: 24.7,
        low_temp: 20,
        max_dhi: null,
        max_temp: 24.7,
        min_temp: 17.2,
        moon_phase: 0.11049,
        moon_phase_lunation: 0.09,
        moonrise_ts: 1677074876,
        moonset_ts: 1677119904,
        ozone: 235.6,
        pop: 15,
        precip: 0.625,
        pres: 1011.7,
        rh: 89,
        slp: 1014.1,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1677068734,
        sunset_ts: 1677109590,
        temp: 20.9,
        ts: 1677045660,
        uv: 6.1,
        valid_date: "2023-02-22",
        vis: 1.717,
        weather: {
          code: 803,
          icon: "c03d",
          description: "Broken clouds",
        },
        wind_cdir: "S",
        wind_cdir_full: "south",
        wind_dir: 178,
        wind_gust_spd: 13,
        wind_spd: 4.9,
      },
      {
        app_max_temp: 26.2,
        app_min_temp: 20.6,
        clouds: 73,
        clouds_hi: 66,
        clouds_low: 71,
        clouds_mid: 14,
        datetime: "2023-02-23",
        dewpt: 19.8,
        high_temp: 25.9,
        low_temp: 20.3,
        max_dhi: null,
        max_temp: 25.9,
        min_temp: 20,
        moon_phase: 0.194054,
        moon_phase_lunation: 0.13,
        moonrise_ts: 1677163174,
        moonset_ts: 1677210141,
        ozone: 230.1,
        pop: 15,
        precip: 0.4375,
        pres: 1016,
        rh: 89,
        slp: 1018.2,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1677155072,
        sunset_ts: 1677196035,
        temp: 21.7,
        ts: 1677132060,
        uv: 5.5,
        valid_date: "2023-02-23",
        vis: 0.748,
        weather: {
          code: 804,
          icon: "c04d",
          description: "Overcast clouds",
        },
        wind_cdir: "S",
        wind_cdir_full: "south",
        wind_dir: 184,
        wind_gust_spd: 8.6,
        wind_spd: 3.5,
      },
      {
        app_max_temp: 25.3,
        app_min_temp: 20.2,
        clouds: 68,
        clouds_hi: 99,
        clouds_low: 65,
        clouds_mid: 0,
        datetime: "2023-02-24",
        dewpt: 19,
        high_temp: 26,
        low_temp: 18.4,
        max_dhi: null,
        max_temp: 26,
        min_temp: 19.4,
        moon_phase: 0.290385,
        moon_phase_lunation: 0.16,
        moonrise_ts: 1677251492,
        moonset_ts: 1677300311,
        ozone: 226.1,
        pop: 20,
        precip: 0.125,
        pres: 1019.8,
        rh: 85,
        slp: 1022,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1677241411,
        sunset_ts: 1677282479,
        temp: 21.7,
        ts: 1677218460,
        uv: 6.3,
        valid_date: "2023-02-24",
        vis: 1.334,
        weather: {
          code: 803,
          icon: "c03d",
          description: "Broken clouds",
        },
        wind_cdir: "S",
        wind_cdir_full: "south",
        wind_dir: 185,
        wind_gust_spd: 4.9,
        wind_spd: 2.3,
      },
      {
        app_max_temp: 24.9,
        app_min_temp: 18.9,
        clouds: 51,
        clouds_hi: 27,
        clouds_low: 51,
        clouds_mid: 0,
        datetime: "2023-02-25",
        dewpt: 18.2,
        high_temp: 25,
        low_temp: 18.7,
        max_dhi: null,
        max_temp: 25,
        min_temp: 18.4,
        moon_phase: 0.393068,
        moon_phase_lunation: 0.19,
        moonrise_ts: 1677339915,
        moonset_ts: 1677390433,
        ozone: 234.4,
        pop: 20,
        precip: 0.0625,
        pres: 1016.6,
        rh: 86,
        slp: 1018.9,
        snow: 0,
        snow_depth: 0,
        sunrise_ts: 1677327748,
        sunset_ts: 1677368923,
        temp: 20.9,
        ts: 1677304860,
        uv: 6.5,
        valid_date: "2023-02-25",
        vis: 6.612,
        weather: {
          code: 803,
          icon: "c03d",
          description: "Broken clouds",
        },
        wind_cdir: "SSE",
        wind_cdir_full: "south-southeast",
        wind_dir: 167,
        wind_gust_spd: 7,
        wind_spd: 3.3,
      },
    ],
    lat: 30.6503,
    lon: -87.9075,
    state_code: "AL",
    timezone: "America/Chicago",
  },
};

class WeatherDay {
  constructor({
    cloud_cover = "",
    air_quality = "",
    dew_point = "",
    datetime = new Date(),
    part_of_day = "",
    precipitation = "",
    pressure = "",
    snowfall = "",
    weather_station = "",
    sunrise = "",
    sunset = "",
    temperature = "",
    feels_like = null,
    timezone = "",
    uv_index = "",
    weather_description = "",
    wind_direction = "",
    wind_speed = "",
    max_wind_speed_gust = "",
    high_temp = null,
    low_temp = null,
  }) {
    this.cloud_cover = `${cloud_cover}%`;
    this.air_quality = `${air_quality} AQI`;
    this.dew_point = `${Math.round(celsiusToFahrenheit(dew_point))} °F`;
    this.datetime = new Date(datetime);
    this.part_of_day = part_of_day
      ? part_of_day === "n"
        ? "Night"
        : "Day"
      : null;
    this.precipitation = `${centimetersToInches(precipitation)} in`;
    this.pressure = `${pressure} hPa`;
    this.snowfall = `${centimetersToInches(snowfall)} in`;
    this.weather_station = weather_station;
    this.sunrise = new Date(sunrise);
    this.sunset = new Date(sunset);
    this.temperature = `${Math.round(celsiusToFahrenheit(temperature))} °F`;
    this.feels_like = feels_like
      ? `${Math.round(celsiusToFahrenheit(feels_like))} °F`
      : "N/A";
    this.timezone = timezone ? timezone : "N/A";
    this.uv_index = Math.round(uv_index * 10) / 10;
    this.weather_description = weather_description ? weather_description : null;
    this.wind_direction = `${wind_direction}°`;
    this.wind_speed = `${msToMph(wind_speed)} mph`;
    this.max_wind_speed_gust = `${msToMph(max_wind_speed_gust)} mph`;
    this.high_temp = high_temp
      ? `${Math.round(celsiusToFahrenheit(high_temp))} °F`
      : null;
    this.low_temp = low_temp
      ? `${Math.round(celsiusToFahrenheit(low_temp))} °F`
      : null;
  }
}

const transformData = (data) => {
  const { location, currentWeather, futureWeather } = data;
  const weatherDataArr = [];
  const currentWeatherData = {};
  currentWeatherData["location"] = location;

  weatherDataArr.push(
    new WeatherDay({
      cloud_cover: currentWeather.clouds,
      air_quality: currentWeather.aqi,
      dew_point: currentWeather.dewpt,
      datetime: currentWeather.datetime.split(":")[0],
      part_of_day: currentWeather.pod,
      precipitation: currentWeather.precip,
      pressure: currentWeather.pres,
      snowfall: currentWeather.snow,
      weather_station: currentWeather.station,
      sunrise: currentWeather.sunrise * 1000, // in Unix time
      sunset: currentWeather.sunset * 1000, // in Unix time
      temperature: currentWeather.temp,
      feels_like: currentWeather.app_temp,
      timezone: currentWeather.timezone,
      uv_index: currentWeather.uv,
      weather_description: currentWeather.weather.description,
      wind_direction: currentWeather.wind_dir,
      wind_speed: currentWeather.wind_spd,
      max_wind_speed_gust: currentWeather.gust,
    })
  );

  futureWeather.data.forEach((day) => {
    weatherDataArr.push(
      new WeatherDay({
        cloud_cover: day.clouds,
        air_quality: day.aqi,
        dew_point: day.dewpt,
        datetime: day.valid_date,
        part_of_day: day.pod,
        precipitation: day.precip,
        pressure: day.pres,
        snowfall: day.snow,
        weather_station: day.station,
        sunrise: day.sunrise,
        sunset: day.sunset,
        temperature: day.temp,
        feels_like: day.app_temp,
        timezone: day.timezone,
        uv_index: day.uv,
        weather_description: day.weather.description,
        wind_direction: day.wind_dir,
        wind_speed: day.wind_spd,
        max_wind_speed_gust: day.gust,
        high_temp: day.high_temp,
        low_temp: day.low_temp,
      })
    );
  });

  currentWeatherData["weatherData"] = weatherDataArr;

  return JSON.stringify(currentWeatherData);
};

console.log(transformData(data));
